version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/nodejs"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "Etc/UTC"
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "Etc/UTC"
