version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/npm"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        versions: [ "21.x" ]

  - package-ecosystem: "docker"
    directory: "/pnpm"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        versions: [ "21.x" ]

  - package-ecosystem: "docker"
    directory: "/yarn"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "node"
        versions: [ "21.x" ]

