version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/npm"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "node"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/pnpm"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "node"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "docker"
    directory: "/yarn"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "node"
        update-types: [ "version-update:semver-major" ]

