version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/npm"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/pnpm"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/yarn"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "Etc/UTC"
